import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useConnectModal, useAccountModal, useChainModal } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
<ConnectButton/>
        <h1 className={styles.title}>
          Welcome to <a href="">RainbowKit</a> + <a href="https://ten.xyz">Ten</a>
        </h1>

        <p className={styles.description}>
          Ten is a Encrypted Layer2 on Ethereum
        </p>
      </main>
    </div>
  );
};

export default Home;
